mysite/urls.py
from django import contrib
from mainsite import views

from django.views.static import serve
from django.urls import re_path
from django.urls import path
from mysite import settings
from myblog.views import depart, homepage, pretty_num, user, admin, task, order, choice, practice, chart, upload

urlpatterns = [
    path('admin/', contrib.admin.site.urls),
    path('main_show/', views.main_show),
    path('post/<slug:slug>/', views.show_post),

    re_path(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    # 首页和登录页面
    path('', homepage.homepage),
    path('login/', homepage.login),
    path('register/', homepage.register),
    path('register/confirm/', homepage.register_confirm),
    path('register/confirm/succeed', homepage.register_confirm_succeed),
    path('logout/', homepage.logout),
    path('image/code/', homepage.image_code),
    path('movie/action/', homepage.movie_action),

    # 管理员管理
    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),
    path('admin/<int:nid>/edit/', admin.admin_edit),
    path('admin/<int:nid>/delete/', admin.admin_delete),
    path('admin/<int:nid>/reset/', admin.admin_reset),

    # 部门管理
    path('depart/list/', depart.depart_list),
    path('depart/add/', depart.depart_add),
    path('depart/delete/', depart.depart_delete),
    path('depart/<int:nid>/edit/', depart.depart_edit),
    path('depart/upload/', depart.depart_upload),

    # 用户管理
    path('user/list/', user.user_list),
    path('user/add/', user.user_add),
    path('user/<int:nid>/edit/', user.user_edit),
    path('user/<int:nid>/delete/', user.user_delete),

    # 靓号管理
    path('pretty_num/list/', pretty_num.pretty_num_list),
    path('pretty_num/add/', pretty_num.pretty_num_add),
    path('pretty_num/<int:nid>/edit/', pretty_num.pretty_num_edit),
    path('pretty_num/<int:nid>/delete/', pretty_num.pretty_num_delete),

    # 任务管理
    path('task/list/', task.task_list),
    path('task/ajax/', task.task_ajax),
    path('task/add/', task.task_add),

    # 订单管理
    path('order/list/', order.order_list),
    path('order/add/', order.order_add),
    path('order/delete/', order.order_delete),
    path('order/detail/', order.order_detail),
    path('order/edit/', order.order_edit),

    # 数据统计
    path('chart/list/', chart.chart_list),
    path('chart/bar/', chart.chart_bar),
    path('chart/pie/', chart.chart_pie),
    path('chart/line/', chart.chart_line),

    # 选号
    path('choices/', choice.choices),
    path('shuangseqiu/', choice.shuangseqiu),
    path('daletou/', choice.daletou),

    # 各种练习
    path('practice/', practice.practice),
    path('dynamic_content/', practice.dynamic_content),
    path('eat_what/', practice.eat_what),

    # 上传文件
    path('upload/form/', upload.upload_form),
    path('upload/modelform/', upload.upload_modelform),

]

myblog/models.py
from django.db import models


# Create your models here.
class AdminInfo(models.Model):
    """管理员表"""
    username = models.CharField(verbose_name='用户名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=64)
    email = models.CharField(verbose_name='邮箱', max_length=64)
    gender_choice = (
        (1, '男'),
        (2, '女')
    )
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choice)
    has_confirmed = models.BooleanField(default=False)

    def __str__(self):
        return self.username


class ConfirmUserEmail(models.Model):
    code = models.CharField(verbose_name='邮箱验证码', max_length=256)
    user = models.CharField(verbose_name='用户名', max_length=32)
    c_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user + ":   " + self.code


class Department(models.Model):
    """部门表"""
    title = models.CharField(verbose_name='部门名称', max_length=32)

    def __str__(self):
        return self.title


class UsersInfo(models.Model):
    """员工表"""
    name = models.CharField(verbose_name='姓名', max_length=16)
    password = models.CharField(verbose_name='密码', max_length=64)
    age = models.IntegerField(verbose_name='年龄')
    account = models.DecimalField(verbose_name='账户余额', max_digits=10, decimal_places=2, default=0)
    # create_time=models.DateTimeField(verbose_name='入职时间')
    create_time = models.DateField(verbose_name='入职时间')

    # 无约束
    # depart_id=models.BigIntegerField(verbose_name='部门id')
    # 1.有约束
    #   -to 与那张表关联
    #   -to_field 表中的那一列关联
    # 2. django自动
    #   -写的depart
    #   -生成数据列 depart_id
    # 3. 部门表被删除
    #       3.1级联删除
    depart = models.ForeignKey(verbose_name='部门', to='Department', to_field='id', on_delete=models.CASCADE)
    #       3.2级联删除
    # depart = models.ForeignKey(verbose_name='部门id', to='Department', to_field='department',null=True,
    # blank=True, on_delete=models.SET_NULL())

    # django中的约束
    gender_choice = ((1, '男'), (2, '女'))
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choice)

    def __str__(self):
        return self.name


class PrettyNumber(models.Model):
    """靓号表"""
    mobile = models.CharField(verbose_name='手机号', max_length=11)
    # 想要为空，null=True,blank=True
    price = models.IntegerField(verbose_name='价格', default=0)
    level_choices = (
        (1, "一级"),
        (2, "二级"),
        (3, "三级"),
        (4, "四级"),
    )
    level = models.SmallIntegerField(verbose_name='级别', choices=level_choices, default=1)
    status_choices = (
        (1, '已占用'),
        (2, '未占用')
    )
    status = models.SmallIntegerField(verbose_name='状态', choices=status_choices, default=2)


class Task(models.Model):
    level_choice = (
        (1, "紧急"),
        (2, "一般"),
        (3, "临时")
    )
    level = models.SmallIntegerField(verbose_name="重要等级", choices=level_choice, default=2)
    title = models.CharField(verbose_name='标题', max_length=64)
    content = models.TextField(verbose_name='任务详情')
    user = models.ForeignKey(verbose_name="负责人", to=AdminInfo, on_delete=models.CASCADE)


class Orders(models.Model):
    order_num = models.CharField(verbose_name='订单号', max_length=32)
    good_name = models.CharField(verbose_name='商品名称', max_length=16)
    price = models.IntegerField(verbose_name='价格')
    status_choice = (
        (1, "已支付"),
        (2, "未支付")
    )
    status = models.SmallIntegerField(verbose_name="支付状态", choices=status_choice, default=2)
    user = models.ForeignKey(verbose_name="买家用户", to=UsersInfo, on_delete=models.CASCADE)


class Boos(models.Model):
    name = models.CharField(verbose_name='姓名', max_length=32)
    age = models.IntegerField(verbose_name='年龄')
    img = models.CharField(verbose_name='头像', max_length=64)


class City(models.Model):
    city = models.CharField(verbose_name='城市', max_length=16)
    population = models.IntegerField(verbose_name='人口')
    logo = models.FileField(verbose_name='图标', max_length=128, upload_to='city/')

myblog/views/admin.py
from django.shortcuts import render, redirect, HttpResponse
from myblog.models import AdminInfo
from myblog.utils.pagination import Pagination
from myblog.utils.form import AdminAddModelForm, AdminEditModelForm, AdminResetModelForm


def admin_list(request):
    """管理员列表"""
    info=request.session.get('info')
    print(info)
    search_username=request.GET.get("search_username", '')
    dic={}
    if search_username:
        dic['username__contains']=search_username

    query_set = AdminInfo.objects.filter(**dic)
    queryset_obj = Pagination(request, query_set)
    content = {
        "query_set": queryset_obj.page_queryset,
        "page_str": queryset_obj.html(),
        "search_username": search_username

    }
    return render(request, 'myblog/admin_list.html', content)


def admin_add(request):
    """添加管理员"""
    if request.method == 'GET':
        form = AdminAddModelForm()
        return render(request, 'myblog/change.html', {"form": form, "title": "新建管理员"})

    form = AdminAddModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'myblog/change.html', {"form": form, "title": "新建管理员"})


def admin_edit(request, nid):
    data_admin_edit = AdminInfo.objects.filter(id=nid).first()
    if not data_admin_edit:
        return render(request, 'myblog/error_page.html')
    title = "编辑管理员"
    if request.method == 'GET':
        form = AdminEditModelForm(instance=data_admin_edit)
        return render(request, 'myblog/change.html', {"form": form, "title": title})

    form = AdminEditModelForm(data=request.POST, instance=data_admin_edit)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'myblog/change.html', {"form": form, "title": title})


def admin_delete(request, nid):
    """删除管理员"""
    AdminInfo.objects.filter(id=nid).delete()
    return redirect('/admin/list/')


def admin_reset(request, nid):
    data_admin_reset = AdminInfo.objects.filter(id=nid).first()
    if not data_admin_reset:
        return render(request, 'myblog/error_page.html')
    title = '重置{}密码'.format(data_admin_reset.username)
    if request.method == 'GET':
        form = AdminResetModelForm()
        return render(request, 'myblog/change.html', {'form': form, 'title': title})
    form = AdminResetModelForm(data=request.POST, instance=data_admin_reset)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'myblog/change.html', {'form': form, 'title': title})

myblog/views/chart.py
from django.shortcuts import render
from django.http import JsonResponse


def chart_list(request):
    return render(request, 'myblog/chart_list.html')


def chart_bar(request):
    result = {
        'status': True,
        'legend': ['王潇猛', '季冬琴'],
        'xAxis': ['1月', '3月', '5月', '7月', '9月', '11月'],
        'series': [
            {
                'name': '王潇猛',
                'type': 'bar',
                'data': [5, 20, 36, 10, 10, 100]
            },
            {
                'name': '季冬琴',
                'type': 'bar',
                'data': [34, 110, 46, 79, 79, 60]
            },
        ]
    }
    return JsonResponse(result)


def chart_pie(request):
    result = {
        'status': True,
        'series': [
            {'value': 1048, 'name': '王潇猛'},
            {'value': 735, 'name': '季冬琴'},
            {'value': 580, 'name': '吴亚楠'},
            {'value': 484, 'name': '杨聪'},
            {'value': 300, 'name': '徐冉'}
        ],
    }
    return JsonResponse(result)


def chart_line(request):
    result = {
        'status': True,
        'series': [820, 932, 901, 934, 1290, 1330, 1320]
    }
    return JsonResponse(result)

myblog/views/choice.py
from django.shortcuts import render
import random
from django.http import JsonResponse


def choices(request):
    return render(request, 'myblog/choices.html')


def shuangseqiu(request):
    red_box = [i for i in range(1, 34)]
    blue_box = [i for i in range(1, 17)]
    red_balls = random.sample(red_box, 6)
    red_balls.sort()
    blue_balls = random.sample(blue_box, 1)
    choice_str = 'red balls：' + '，'.join(map(str, red_balls)) + '  ' + "blue balls：" + '，'.join(map(str, blue_balls))
    return JsonResponse({'message': choice_str})


def daletou(request):
    red_box = [i for i in range(1, 36)]
    blue_box = [i for i in range(1, 13)]
    red_balls = random.sample(red_box, 5)
    red_balls.sort()
    blue_balls = random.sample(blue_box, 2)
    blue_balls.sort()
    choice_str = 'front area：' + '，'.join(map(str, red_balls)) + '  ' + "back area：" + '，'.join(map(str, blue_balls))
    return JsonResponse({'message': choice_str})

myblog/views/depart.py
from django.shortcuts import render, redirect, HttpResponse
from myblog import models
from openpyxl import load_workbook


def depart_list(request):
    """部门列表"""
    depart_list_info = models.Department.objects.all()
    return render(request, 'myblog/depart_list.html', {'depart_list_info': depart_list_info})


def depart_add(request):
    """添加部门"""
    if request.method == 'GET':
        return render(request, 'myblog/depart_add.html')
    department = request.POST.get('department')
    models.Department.objects.create(title=department)
    return redirect('/depart/list/')


def depart_delete(request):
    """删除部门"""
    nid = request.GET.get('nid')
    models.Department.objects.filter(id=nid).delete()
    return redirect('/depart/list/')


def depart_edit(request, nid):
    """编辑部门"""
    if request.method == 'GET':
        edit_depart = models.Department.objects.filter(id=nid).first()
        return render(request, 'myblog/depart_edit.html', {'edit_depart': edit_depart})

    new_depart = request.POST.get('new_depart')
    models.Department.objects.filter(id=nid).update(title=new_depart)
    return redirect('/depart/list/')


def depart_upload(request):
    # 1.获取用户上传的文件
    file_obj = request.FILES.get('exc')
    # 2. 对象传递给openpyxl,由openpyxl读取文件内容
    wb = load_workbook(file_obj)
    sheet = wb.worksheets[0]
    # 3.循环读取每一行数据
    for row in sheet.iter_rows(min_row=2):
        text = row[0].value
        exist = models.Department.objects.filter(title=text).exists()
        if not exist:
            models.Department.objects.create(title=text)
    return redirect('/depart/list/')

myblog/views/homepage.py
from django.shortcuts import render, redirect, HttpResponse
from myblog.utils.form import LoginForm, RegisterModelForm
from myblog import models
from myblog.utils.code import check_code
from io import BytesIO
from datetime import datetime, timedelta
from myblog.utils.encrypt import md5
from myblog.utils.send_email import send_email
from django.conf import settings


# Create your views here.
def homepage(request):
    return render(request, 'myblog/homepage.html')


def login(request):
    """用户登录"""
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'myblog/login.html', {"form": form})
    form = LoginForm(data=request.POST)
    if form.is_valid():
        # 校验验证码

        code = form.cleaned_data.pop('code')
        req_code = request.session.get('code_string', '')
        if code.upper() != req_code.upper():
            form.add_error("code", '验证码错误')
            return render(request, 'myblog/login.html', {"form": form})
        # 校验成功，获得用户输入的用户名和密码，从数据库中去比对
        user_data = models.AdminInfo.objects.filter(**form.cleaned_data).first()
        if not user_data:
            # 如果输入错误，弹出提示信息
            form.add_error("password", "输入的用户名或者密码错误 ")
            return render(request, 'myblog/login.html', {"form": form})
        # 校验邮箱是否确认
        if user_data.has_confirmed == 0:
            form.add_error('password', '您的注册邮箱未确认，请前往邮箱确认后重新登录')
            return render(request, 'myblog/login.html', {"form": form})
        # 信息输入正确
        # 网站随机生成字符串，写到用户浏览器的cookies，再写到session中
        request.session["info"] = {"id": user_data.id, "username": user_data.username}
        # 设置session维持时间3天
        request.session.set_expiry(60 * 60 * 24 * 3)
        return redirect('/')
    return render(request, 'myblog/login.html', {"form": form})


def make_code_string(username):
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    code = md5(username) + md5(now)
    return code


def register(request):
    if request.method == 'GET':
        form = RegisterModelForm()
        return render(request, 'myblog/register.html', {"form": form})
    form = RegisterModelForm(data=request.POST)
    if form.is_valid():
        code = form.cleaned_data.pop('code')
        session_code = request.session.get('code_string', '')
        if code.upper() != session_code.upper():
            form.add_error("code", '验证码错误')
            return render(request, 'myblog/register.html', {"form": form})
        form.save()

        email_code = make_code_string(form.cleaned_data.get('username'))
        send_email(form.cleaned_data.get('email'), email_code)
        models.ConfirmUserEmail.objects.create(user=form.cleaned_data.get('username'), code=email_code)
        return redirect('/login/')
    return render(request, 'myblog/register.html', {"form": form})


def register_confirm(request):
    code = request.GET.get('code', '')
    try:
        confirm = models.ConfirmUserEmail.objects.filter(code=code).first()
        user_data = models.AdminInfo.objects.filter(username=confirm.user).first()
    except:
        message = '无效的确认请求！请检查邮件中注册地址是否正确'
        return render(request, 'myblog/register_confirm_succeed.html', {'message': message})

    c_time = confirm.c_time
    now = datetime.now()
    if now > c_time + timedelta(days=settings.CONFIRM_DAYS):
        confirm.delete()
        user_data.delete()
        message = '您的邮件已经过期，请重新注册！'
        return render(request, 'myblog/register_confirm_succeed.html', {'message': message})
    user_data.has_confirmed = True
    user_data.save()
    confirm.delete()
    message = '感谢确认，请使用账户登录！'
    return render(request, 'myblog/register_confirm_succeed.html', {'message': message})


def register_confirm_succeed(request):
    return render(request, 'myblog/register_confirm_succeed.html')


def logout(request):
    request.session.clear()
    return redirect('/login/')


def image_code(request):
    # 调用pillow函数check_code生成图片
    img, code_string = check_code()
    # 将code_string 写入到session中，以便后续获取验证码校验
    request.session['code_string'] = code_string
    # 给session设置60s超时
    request.session.set_expiry(60)
    # 写入内存(Python3)
    stream = BytesIO()
    img.save(stream, 'png')
    return HttpResponse(stream.getvalue())


def movie_action(request):
    return render(request, 'myblog/movie_action.html')

myblog/views/practice.py
from django.shortcuts import render


def practice(request):
    return render(request, 'myblog/practice.html')


def dynamic_content(request):
    return render(request, 'myblog/dynamic_content.html')


def eat_what(request):
    return render(request,'myblog/eat_what.html')

templates/myblog/admin_list.html
{% extends 'myblog/layout.html' %}
{% block content %}
    <div>
        <div class="container">
            <div style="margin-bottom: 20px" class="clearfix">
                <div style="float: left">
                    <a class="btn btn-success" href="/admin/add/">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        新建管理员账号
                    </a>
                </div>
                <div style="float: right">
                    <form class="form-inline" method="get">
                        <div class="form-group">
                            <input type="text" class="form-control" name='search_username' value="{{ search_username }}" placeholder="请输入您要查找的用户名">
                        </div>
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                    </form>
                </div>
            </div>
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                    管理员列表
                </div>

                <!-- Table -->
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>用户名</th>
                        <th>密码</th>
                        <th>重置密码</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in query_set %}
                        <tr>
                            <td>{{ item.id }}</td>
                            <td>{{ item.username }}</td>
                            <td>*******</td>
                            <td>
                                <a href="/admin/{{ item.id }}/reset/" class="btn btn-primary btn-xs">重置密码</a>
                            </td>
                            <td>
                                <a href="/admin/{{ item.id }}/edit/" class="btn btn-info btn-xs">编辑</a>
                                <a href="/admin/{{ item.id }}/delete/" class="btn btn-danger btn-xs">删除</a>
                            </td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <ul class="pagination">
                {{ page_str }}
            </ul>
        </div>
    </div>
{% endblock %}

templates/myblog/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的个人笔记</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.css' %}">
    <style>
        .loginForm {
            /*边框高度*/
            height: 450px;
            /*边框宽度*/
            width: 500px;
            /*边框颜色*/
            border: #4d4d4d solid 1px;
            /*边框圆角*/
            border-radius: 10px;
            /*阴影 水平方向，竖直方向，模糊距离*/
            box-shadow: 5px 5px 5px #4d4d4d;
            /*上边界距离*/
            margin-top: 80px;
            /*左边界距离：自动*/
            margin-left: auto;
            /*右边界距离：自动*/
            margin-right: auto;
            /*用户名、密码间距*/
            padding: 20px 40px;
        }

        /*将用户登录置于中间*/
        .loginForm h2 {
            text-align: center;
        }

        /*修改button属性*/
        .button {
            text-align: center;
            vertical-align: middle;
        }
    </style>

</head>
<body>
<div class="container" style="margin-top: 100px">
    <div class="row">
        <div class="col-lg-6">
            <img src="{% static "img/pic1.jpg" %}" style="width: 70%">
        </div>
        <div class="col-lg-6 bg-white">
            <div class="loginForm">
                <h2>用户登录</h2>
                <form method="post" novalidate>
                    {% csrf_token %}
                    <div class="form-group">
                        <label>用户名</label>
                        {{ form.username }}
                        <span style="color: red">{{ form.username.errors.0 }}</span>
                    </div>
                    <div class="form-group">
                        <label>密码</label>
                        {{ form.password}}
                        <span style="color: red">{{ form.password.errors.0 }}</span>
                    </div>
                    <div class="form-group">
                        <label for="id_code">验证码</label>
                        <div class="row">
                            <div class="col-xs-7">
                                {{ form.code }}
                                <span style="color: red">{{ form.code.errors.0 }}</span>
                            </div>
                            <div class="col-xs-5">
                                <img id="image_code" src="/image/code/" alt="出错了">
                            </div>
                        </div>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox"> 记住密码
                        </label>
                    </div>
                    <div>
                        无账号，请<a href="/register/" >注册</a>
                    </div>
                    <div class="button">
                        <input type="submit" class="btn btn-primary" value="登 录"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'js/jquery-3.6.1.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>

templates/myblog/pretty_num_list.html
{% extends 'myblog/layout.html' %}
{% block content %}
    <div>
        <div class="container">
            <div style="margin-bottom: 20px" class="clearfix">
                <div style="float: left">
                    <a class="btn btn-success" href="/pretty_num/add/">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        新建靓号
                    </a>
                </div>
                <div style="float: right">
                    <form class="form-inline" method="get">
                        <div class="form-group">
                            <input type="text" class="form-control" name='search_num' value="{{ search_data }}"
                                   placeholder="请输入您要查找的手机号">
                        </div>
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                    </form>
                </div>
            </div>
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                    靓号列表
                </div>

                <!-- Table -->
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>手机号</th>
                        <th>价格</th>
                        <th>水平</th>
                        <th>状态</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in query_set %}
                        <tr>
                            <td>{{ item.id }}</td>
                            <td>{{ item.mobile }}</td>
                            <td>{{ item.price }}</td>
                            <td>{{ item.get_level_display }}</td>
                            <td>{{ item.get_status_display }}</td>
                            <td>
                                <a href="/pretty_num/{{ item.id }}/edit/" class="btn btn-info btn-xs">编辑</a>
                                <a href="/pretty_num/{{ item.id }}/delete/" class="btn btn-danger btn-xs">删除</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="clearfix">
                <ul class="pagination">
                    {{ page_str }}

                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/myblog/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>我的个人笔记</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.css' %}">
    <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <style>
        .loginForm {
            /*边框高度*/
            height: 450px;
            /*边框宽度*/
            width: 500px;
            /*边框颜色*/
            border: #4d4d4d solid 1px;
            /*边框圆角*/
            border-radius: 10px;
            /*阴影 水平方向，竖直方向，模糊距离*/
            box-shadow: 5px 5px 5px #4d4d4d;
            /*上边界距离*/
            margin-top: 80px;
            /*左边界距离：自动*/
            margin-left: auto;
            /*右边界距离：自动*/
            margin-right: auto;
            /*用户名、密码间距*/
            padding: 20px 40px;
        }

        /*将用户登录置于中间*/
        .loginForm h2 {
            text-align: center;
        }

        /*修改button属性*/
        .button {
            text-align: center;
            vertical-align: middle;
        }
    </style>

</head>
<body>
<div class="container" style="margin-top: 100px">
    <div class="col-md-4 col-md-offset-4">
        <h2 class="text-center">欢迎注册</h2>
        <form method="post" novalidate>
            {% if message %}
                  <div class="alert alert-warning">{{ message }}</div>
            {% endif %}
            {% csrf_token %}
            <div class="form-group">
                <label>{{ form.username.label }}</label>：{{ form.username }}
                <span style="color: red">{{ form.username.errors.0 }}</span>
            </div>
            <div class="form-group">
                <label>{{ form.password.label }}</label>：{{ form.password }}
                <span style="color: red">{{ form.password.errors.0 }}</span>
            </div>
            <div class="form-group">
                <label>{{ form.confirm_password.label }}</label>：{{ form.confirm_password }}
                <span style="color: red">{{ form.confirm_password.errors.0 }}</span>
            </div>
            <div class="form-group">
                <label>{{ form.gender.label }}</label>：{{ form.gender }}
                <span style="color: red">{{ form.gender.errors.0 }}</span>
            </div>
            <div class="form-group">
                <label for="id_code">验证码</label>
                <div class="row">
                    <div class="col-xs-7">
                        {{ form.code }}
                        <span style="color: red">{{ form.code.errors.0 }}</span>
                    </div>
                    <div class="col-xs-5">
                        <img id="image_code" src="/image/code/">
                    </div>

                </div>
            </div>
            <div class="form-group">
                <label>{{ form.email.label }}</label>：{{ form.email }}
                <span style="color: red">{{ form.email.errors.0 }}</span>
            </div>
            <button type="reset" class="btn btn-default pull-left">重置</button>
            <button type="submit" class="btn btn-primary pull-right">提交</button>

        </form>
    </div>

</div>
<script src="{% static 'js/jquery-3.6.1.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>